# Created by 弱弱的胖橘猫丷

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE       := dts_sounds
LOCAL_SRC_FILES    := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR_APPS)
LOCAL_CERTIFICATE := media
#LOCAL_REQUIRED_MODULES := 
include $(BUILD_PREBUILT) 


